### ISSUE TITLE
Fix Submit button bug (Posts don't show until you log out.)

### ISSUE THREAD

**Issue by jltomas** [cpe308-309/TheFellowship#103]

**Comment by jltomas** [comment]
More details:

The core of this bug might be located in js/myScripts.js:

function sendSignOut () {
    $.ajax({
        url: domain + "/logout",
        type: "POST",
        headers: {
            "Content-Type": "application/json",
        },
        dataType: "text",
        window.sessionStorage.token=""
    });
}

With this block of code, the "Create User" button does not work. When modified to this: 

function sendSignOut () {
    window.sessionStorage.token=""
}

"Create User" works, but the bug described in the title of this issue occurs. When modified to this:

function sendSignOut () {
}

it is essentially functionally the same result as 

function sendSignOut () {
    window.sessionStorage.token=""
}

**Comment by michellesfc** [comment]
The problem with the post not showing is because the refreshPost method in myScripts.js is not working. 

This can be fixed by just having this one statement in the method.
$("#listArea").append(template(object));

**Comment by michellesfc** [comment]
Ignore that comment.

**Comment by michellesfc** [comment]
In the myScripts.js file, line 203 should be $("#listArea").append(template(data));
