### ISSUE TITLE
Enable comments- Frontend

### ISSUE THREAD

**Issue by melyou** [cpe308-309/TheFellowship#110]

**Comment by jltomas** [comment]
Is this "put a text box in the comment div on front end", "store the comments in a database on back-end" or like a mix of both?

**Comment by michellesfc** [comment]
This one should be the "put a text box in the comment div on front end". I'll make a separate issue for the backend

**Comment by jltomas** [comment]
This is a quick fix, should be done hopefully by tomorrow night. Spring Dance show is taking up a ton of time this week haha.

**Comment by michellesfc** [comment]
I added the backend stuff for the comments in the comments branch. Please work on that branch when you are working on this issue.

**Comment by jltomas** [comment]
Will do! thank you

**Comment by devmart10** [comment]
Justin, did you ever do it? I'm about to work on it now

**Comment by jltomas** [comment]
IP now.

**Comment by michellesfc** [comment]
To create a comment for a Newsfeed post make a POST request to: /comments/{id}
The id is the id of the Newsfeed post that you want to add a comment to.
The input for a comment is a message, so the JSON for creating a post is:
{
"message": "This is a comment"
}

To retrieve the comments for a post make a GET request to : /comments/{id}
The id is the id of the Newsfeed post that you want the comments for.
You should get a list of comments as the response.

**Comment by jltomas** [comment]
I'll make a separate issue for this.
