### ISSUE TITLE
Bug: Order posts in chronological order

### ISSUE THREAD

**Issue by devmart10** [cpe308-309/TheFellowship#128]
posts need to be returned from the database in order from most recent to oldest.

**Comment by michellesfc** [comment]
in backend return the list of posts in chronological order

**Comment by melyou** [comment]
- NewsfeedPost class modified to implement Comparator
- compare() method sorts posts from most recent to oldest with compareTo()

- Collections.sort() done on ArrayList of posts before return (in Controller)

**Comment by jltomas** [comment]
Just a heads up, the addition of comments now breaks this again. When you enter a comment, I'm guessing the post timestamp somehow gets updated, and the post you commented on gets sent to the bottom now.
