### ISSUE TITLE
Ability to remove posts

### ISSUE THREAD

**Issue by devmart10** [cpe308-309/TheFellowship#63]

**Comment by melyou** [comment]
Users remove their own posts (?)
Can admin do this too?

**Comment by jltomas** [comment]
Yes. Removing inappropriate posts was the idea that spawned this particular issue

**Comment by jltomas** [comment]
I will add a remove post button. I think handling whether or not that button is there is easily handled by the latest commit of the different user types, but probably push that to the next milestone.

**Comment by devmart10** [comment]
is this for next time then?

**Comment by jltomas** [comment]
Functionality, most likely yes
