### ISSUE TITLE
Create user profile page

### ISSUE THREAD

**Issue by devmart10** [cpe308-309/TheFellowship#64]

**Comment by melyou** [comment]
- Skeleton for user profile page design (Mel)

**Comment by jltomas** [comment]
Double assigning melinda on this so that i can focus on fixing the stupid filter panel in place and fill in the blanks on this later (thanks melinda! :))

**Comment by melyou** [comment]
Created input fields for user information! Wasn't too sure about how we wanted the layout to look like

**Comment by devmart10** [comment]
Wait so this is for creating/updating the profile? Looks great, but  I misunderstood and thought it would show the user profile. Do we need a new issue for making a display page?

**Comment by jltomas** [comment]
@devmart10 you are correct, this was supposed to be the user profile, lol

**Comment by melyou** [comment]
OH NO Sorry!! I misunderstood what Justin meant!
