### ISSUE TITLE
Limit users to only liking a post once

### ISSUE THREAD

**Issue by devmart10** [cpe308-309/TheFellowship#66]

**Comment by devmart10** [comment]
We need a back-end change to be able to accommodate a list of Users, they I can check that list

**Comment by michellesfc** [comment]
The backend takes care of this in the Controller class. When a user likes a post, the controller checks if the user already liked it. If the user liked the post, the user is removed from the list. If the user did not like the post before, then the user is added to the list. This is all done in the incrementLike function in Controller.java
