### ISSUE TITLE
Landing page ("create user", "login")

### ISSUE THREAD

**Issue by devmart10** [cpe308-309/TheFellowship#71]

**Comment by devmart10** [comment]
Integrate Michelle's page

**Comment by michellesfc** [comment]
The landing page is in the resources/static folder. The map is from Google Maps API. We can add a heat map layer on top of it. Also, the color scheme for the landing page can be changed if needed. The Enter button on the header bar redirects to localhost:8080 (we need to change it to the heroku website later).  We should also fill the landing page with information about our website.
