### ISSUE TITLE
Create stats class

### ISSUE THREAD

**Issue by michellesfc** [cpe308-309/TheFellowship#79]

**Comment by melyou** [comment]
- Number of posts per tag
- How many people from Munich/Cal Poly (by email)
- How many Professors/Students (when they sign up choose)...later when we differentiate between users

**Comment by melyou** [comment]
FOR NOW:

- Can get total number of posts
- Total number of Users
- Total number of calpoly users (based on email): can modify or add to for later Milestones
- gets total posts from specified tag string
