### ISSUE TITLE
Keep filters on screen during scrolling (lock)

### ISSUE THREAD

**Issue by devmart10** [cpe308-309/TheFellowship#93]

**Comment by jltomas** [comment]
self reminder: https://stackoverflow.com/questions/28340054/bootstrap-keep-div-fixed-after-scrolling-to-it

**Comment by jltomas** [comment]
Devon found the fix even though i spent hours researching it -_-. He used "container-fluid" which my research told me was deprecated. So I'm pretty unhappy about that.

**Comment by devmart10** [comment]
Lol it's so simple I didn't even think of it. I was researching how the container padded stuff and then I saw that "container-fluid has no side padding" so I realized that's exactly what we needed
